"""add case management fields

Revision ID: fefb2544daa0
Revises: b01773e488bc
Create Date: 2026-07-22 02:05:59.567480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefb2544daa0'
down_revision: Union[str, Sequence[str], None] = 'b01773e488bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('resolution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolution')
    op.drop_column('incidents', 'due_date')
    op.drop_column('incidents', 'assigned_to')
    op.drop_column('incidents', 'priority')
    # ### end Alembic commands ###
